drop table account_icon cascade;
drop sequence account_icon_sequence cascade;
drop table account_type cascade;
drop sequence account_type_sequence cascade;
drop table account cascade;
drop sequence account_sequence cascade;
drop table account_statement cascade;
drop sequence account_statement_sequence cascade;
drop table user_detail cascade;
drop sequence user_detail_sequence;
drop table user_account cascade;
drop sequence user_account_sequence cascade;
drop table transaction cascade;