# PostgreSQL Connection Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_manager
spring.datasource.username=postgres
spring.datasource.password=admin

# logging
logging.file.name=/finance_manager_application/logs/transaction-service.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Connection Pool Properties
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# server config
server.port=5004