spring.application.name=api_gateway
server.port=5001
# Disable R2DBC auto-configuration
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration


# PostgreSQL Connection Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_manager
spring.datasource.username=postgres
spring.datasource.password=admin