spring.application.name=api_gateway

# logging
logging.file.path=/finance_manager_application/logs
logging.file.name=/finance_manager_application/logs/api-gateway.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.file-name-pattern=/finance_manager_application/logs/api-gateway.%d{yyyy-MM-dd}.log
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=1GB