-- user_detail: sample data
-- Password hash is bcrypt("admin") - api-gateway's UserServiceImpl.authenticateUser
-- uses BCryptPasswordEncoder.matches(), which never matches a plaintext value
-- (silently returns false rather than throwing), so a plaintext 'admin' here
-- would make every sample user permanently unable to log in. Generated by
-- actually signing up a throwaway user with password "admin" via api-gateway's
-- real /auth/signup and copying its resulting hash, so it's the exact same
-- encoder/cost-factor this app uses (not a hash from an unrelated tool).
INSERT INTO user_detail (id, username, password) VALUES
(1, 'Rishi Ghai', '$2a$10$at/4PR9ngiuCbShS6OPqsOw6Kwj4C8ury.3RA6NKzhbhud48XrdJi'),
(2, 'Sujata Ghai', '$2a$10$at/4PR9ngiuCbShS6OPqsOw6Kwj4C8ury.3RA6NKzhbhud48XrdJi'),
(3, 'Naresh Ghai', '$2a$10$at/4PR9ngiuCbShS6OPqsOw6Kwj4C8ury.3RA6NKzhbhud48XrdJi'),
(4, 'Rohan Ghai', '$2a$10$at/4PR9ngiuCbShS6OPqsOw6Kwj4C8ury.3RA6NKzhbhud48XrdJi');

SELECT setval('user_detail_sequence', (SELECT MAX(id) FROM user_detail));
