import os

from model.account_statement import AccountStatementExtension
from model.account_statement_upload_request import AccountStatementUploadRequest
from service.statement_reader.bank_savings.hdfc_savings_account_pdf_statement_reader import (
    HdfcSavingsAccountPdfStatementReader,
)

# The synthetic fixture generated by scripts/generate_dummy_statement_fixtures.py
# (see jira/JIRA_11.md) - not a real personal statement, safe to commit and
# reproducible on any checkout/CI. Reuses test-automation's fixtures
# directory so there's one canonical copy, same as every other reader's
# fixture under JIRA_8.
_HDFC_PDF_FIXTURE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "..", "..",
    "..", "test-automation", "src", "test", "resources", "fixtures", "statements", "hdfc.pdf",
)


def load_fixture_bytes():
    with open(_HDFC_PDF_FIXTURE_PATH, "rb") as f:
        return f.read()


class TestReadStatement:

    def test_parses_the_synthetic_fixture_into_transactions(self):
        reader = HdfcSavingsAccountPdfStatementReader()
        request = AccountStatementUploadRequest(
            account_id=1, user_id=1, user_account_id=1,
            file="", file_name="hdfc.pdf", file_extension="pdf", request_id="test-1",
        )

        transactions = reader.read_statement(request=request, file=load_fixture_bytes())

        assert len(transactions) == 4
        for t in transactions:
            assert t.user_account_id == 1
            assert t.closing_balance is not None
            assert t.is_debit_or_credit in ("DR", "CR")
            assert t.debit_or_credit_amount > 0

    def test_derives_debit_or_credit_from_the_balance_delta_not_from_column_position(self):
        # The real HDFC PDF export collapses the Withdrawal/Deposit columns
        # into one flattened text position per line - direction has to be
        # inferred from whether the running balance went up or down.
        reader = HdfcSavingsAccountPdfStatementReader()
        request = AccountStatementUploadRequest(
            account_id=1, user_id=1, user_account_id=1,
            file="", file_name="hdfc.pdf", file_extension="pdf", request_id="test-2",
        )

        transactions = reader.read_statement(request=request, file=load_fixture_bytes())

        balance = 50000.0  # the fixture's own opening balance (see build_hdfc_pdf)
        for t in transactions:
            balance = balance + t.debit_or_credit_amount if t.is_debit_or_credit == "CR" else balance - t.debit_or_credit_amount
            assert abs(balance - t.closing_balance) < 0.01


class TestReaderIdentity:

    def test_reports_its_account_version_and_extension(self):
        reader = HdfcSavingsAccountPdfStatementReader()

        assert reader.account_id() == 1
        assert reader.version() == 1
        assert reader.extension() == AccountStatementExtension.pdf
