package com.finance.manager.test_automation.steps.backend;

import com.finance.manager.test_automation.config.EnvironmentConfig;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.Base64;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Uploads a synthetic fixture from
 * test-automation/src/test/resources/fixtures/statements/ - one per
 * statement-loader reader (bank/broker + extension), generated by
 * scripts/generate_dummy_statement_fixtures.py and verified against the
 * real reader classes at generation time (see jira/JIRA_8.md). Not a real
 * personal statement - safe to commit, reproducible on any checkout/CI.
 */
public class StatementUploadBackendSteps {

    private static final int DEMO_USER_ID = 1;

    private final EnvironmentConfig environmentConfig;
    private final RestTemplate restTemplate = new RestTemplate();

    private ResponseEntity<List> uploadResponse;

    public StatementUploadBackendSteps(EnvironmentConfig environmentConfig) {
        this.environmentConfig = environmentConfig;
    }

    @When("I upload the {string} fixture for account {int} user_account {int} to statement-loader")
    public void i_upload_the_fixture(String fixtureFilename, int accountId, int userAccountId) {
        String base64 = encodeFixtureAsBase64(fixtureFilename);
        String extension = fixtureFilename.substring(fixtureFilename.lastIndexOf('.') + 1);

        Map<String, Object> request = Map.of(
                "account_id", accountId,
                "user_id", DEMO_USER_ID,
                "user_account_id", userAccountId,
                "file", base64,
                "file_name", fixtureFilename,
                "file_extension", extension,
                "request_id", "test-upload-" + fixtureFilename + "-" + System.currentTimeMillis());

        uploadResponse = restTemplate.postForEntity(
                environmentConfig.statementLoaderUrl() + "/statement/upload/v1/",
                List.of(request), List.class);
    }

    private String encodeFixtureAsBase64(String fixtureFilename) {
        try {
            byte[] bytes = new ClassPathResource("fixtures/statements/" + fixtureFilename)
                    .getInputStream().readAllBytes();
            return Base64.getEncoder().encodeToString(bytes);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    @Then("the upload response has status {int} and reports success")
    public void the_upload_response_reports_success(int expectedStatus) {
        assertThat(uploadResponse.getStatusCode().value()).isEqualTo(expectedStatus);
        Map result = (Map) uploadResponse.getBody().get(0);
        assertThat(result.get("status")).isEqualTo(true);
    }
}
